"use client";
import { useEffect, useState } from "react";
import { SettingsTabs } from "@/app/components/settings-tabs";
import { cn } from "@/lib/utils";
import { Card, CardContent } from "@/components/ui/card";
import { useAdminAuth } from "@/contexts/admin-auth-provider";
import { apiRequest } from "@/lib/api/client";

type Session={id:string;browser:string;os:string;deviceType:string;ip:string;location:string;lastActiveAt:string;current:boolean};
function relative(value:string){const seconds=Math.floor((Date.now()-new Date(value).getTime())/1000);if(seconds<90)return"Active now";if(seconds<3600)return`${Math.floor(seconds/60)} minutes ago`;if(seconds<86400)return`${Math.floor(seconds/3600)} hours ago`;return`${Math.floor(seconds/86400)} days ago`;}
export default function SettingsPage(){
 const{admin,refreshSession}=useAdminAuth();const[sessions,setSessions]=useState<Session[]>([]);const[setup,setSetup]=useState<any>(null);const[code,setCode]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function load(){try{const r=await apiRequest<{sessions:Session[]}>("admin/security/sessions",{auth:true});setSessions(r.sessions);}catch(e:any){setMessage(e.message||"Unable to load devices.");}}
 useEffect(()=>{void load();},[]);
 async function toggle2fa(){setMessage("");setBusy(true);try{if(admin?.twoFactorEnabled){await apiRequest("admin/security/2fa/disable",{method:"POST",json:{code},auth:true});setSetup(null);setCode("");setMessage("Two-factor authentication disabled.");await refreshSession();}else{setSetup(await apiRequest("admin/security/2fa/setup",{method:"POST",auth:true}));setMessage("Scan the QR code and enter the 6-digit code to finish setup.");}}catch(e:any){setMessage(e.message||"Unable to update two-factor authentication.");}finally{setBusy(false);}}
 async function verify(){setBusy(true);setMessage("");try{await apiRequest("admin/security/2fa/verify",{method:"POST",json:{code},auth:true});setSetup(null);setCode("");setMessage("Two-factor authentication enabled.");await refreshSession();}catch(e:any){setMessage(e.message||"Invalid code.");}finally{setBusy(false);}}
 async function logoutSession(id:string){await apiRequest(`admin/security/sessions/${id}`,{method:"DELETE",auth:true});await load();}
 async function logoutAll(){await apiRequest("admin/security/sessions",{method:"DELETE",auth:true});await load();setMessage("All other devices have been logged out.");}
 return <Card className="mx-auto w-full max-w-[604px] rounded-[20px] border border-[#edf4f8] bg-white"><CardContent className="space-y-5 p-4 sm:space-y-6 sm:p-6 md:space-y-8 md:p-10 lg:p-12"><div className="flex justify-center"><SettingsTabs/></div>
 {message?<p className="rounded-[12px] bg-[#edf4f8] px-3 py-2 text-[12px] text-[#050a0e]">{message}</p>:null}
 <div className="rounded-[12px] border border-[#cfe2ec] p-4 sm:p-5 md:px-6 md:py-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[14px] font-medium text-[#050a0e]">2-step verification</p><p className="mt-1 text-[12px] text-[#919191]">Protect your account with an authenticator app.</p></div><button aria-checked={Boolean(admin?.twoFactorEnabled)} aria-label="Toggle two-step verification" className="relative h-[22px] w-[42px] shrink-0 rounded-full" onClick={toggle2fa} role="switch" disabled={busy}><span className={cn("absolute inset-0 rounded-full",admin?.twoFactorEnabled?"bg-[#5c60cc]":"bg-[#e3e8ec]")}/><span className={cn("absolute top-1/2 z-10 size-[18px] -translate-y-1/2 rounded-full bg-white shadow",admin?.twoFactorEnabled?"left-[calc(100%-20px)]":"left-0.5")}/></button></div>
 {setup?<div className="mt-5 grid gap-4 border-t border-[#cfe2ec] pt-5 sm:grid-cols-[150px_1fr]"><img src={setup.qrCodeDataUrl} alt="2FA QR code" className="size-[150px] rounded-[12px] border border-[#cfe2ec]"/><div className="space-y-3"><p className="text-[12px] text-[#575757]">Scan this QR code with Google Authenticator, Microsoft Authenticator, Authy, or another TOTP app.</p><input value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" maxLength={6} placeholder="000000" className="h-10 w-full rounded-[12px] border border-[#cfe2ec] px-3 text-[12px] outline-none focus:border-[#5c60cc]"/><button onClick={verify} disabled={busy||code.length!==6} className="h-10 rounded-[12px] bg-[#5c60cc] px-5 text-[12px] font-medium text-white disabled:opacity-50">Verify and enable</button></div></div>:admin?.twoFactorEnabled?<div className="mt-4 border-t border-[#cfe2ec] pt-4"><p className="mb-2 text-[11px] text-[#919191]">Enter a current authenticator code before turning 2FA off.</p><input value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" maxLength={6} placeholder="Authenticator code" className="h-10 w-full rounded-[12px] border border-[#cfe2ec] px-3 text-[12px] outline-none focus:border-[#5c60cc]"/></div>:null}
 </div>
 <div><p className="mb-3 text-[12px] font-medium text-[#050a0e]">Logged Devices</p><div className="space-y-5 rounded-[12px] border border-[#cfe2ec] p-4 sm:p-5 md:px-6 md:py-6">{sessions.length?sessions.map((device)=><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between" key={device.id}><div className="min-w-0"><p className="text-[14px] font-medium text-[#050a0e]">{device.location}</p><p className={cn("mt-1 text-[12px]",device.current?"text-[#14ae5c]":"text-[#919191]")}>{device.current?"Active now":relative(device.lastActiveAt)} • {device.browser} • {device.os}</p><p className="mt-1 text-[10px] text-[#919191]">{device.deviceType} · IP {device.ip}</p></div>{!device.current?<button onClick={()=>logoutSession(device.id)} className="h-10 rounded-[12px] bg-[#edf4f8] px-4 text-[12px] font-medium">Log out</button>:null}</div>):<p className="text-[12px] text-[#919191]">No active device sessions found.</p>}<div className="flex justify-center pt-1"><button onClick={logoutAll} className="h-10 rounded-[12px] bg-[#5c60cc] px-5 text-[12px] font-medium text-white">Log out all other devices</button></div></div></div>
 </CardContent></Card>;
}
