import { NextRequest } from "next/server";
import { GovernanceProposal, GovernanceVote } from "@/models";
import { requireAdmin } from "@/lib/server/auth";
import { handleRouteError, HttpError, noContent, ok, readJson } from "@/lib/server/http";
import { proposalJson } from "@/lib/server/common-serializers";
import { recordActivity } from "@/lib/server/activity";

async function withStats(proposal:any,adminId:string){const votes=await GovernanceVote.find({proposalId:proposal._id}).lean();const stats:any={for:0,against:0,abstain:0,total:0};let currentVote=null;for(const vote of votes as any[]){stats[vote.choice]+=vote.votingPower;stats.total+=vote.votingPower;if(String(vote.voterAdminId)===adminId)currentVote=vote.choice;}return proposalJson(proposal,stats,currentVote);}
export async function GET(request:NextRequest,context:{params:Promise<{proposalId:string}>}){try{const{admin}=await requireAdmin(request,"governance.view");const{proposalId}=await context.params;const proposal=await GovernanceProposal.findById(proposalId).populate("propertyId","name").populate("proposedBy","fullName email");if(!proposal)throw new HttpError(404,"NOT_FOUND","Proposal not found.");return ok(await withStats(proposal,String(admin._id)));}catch(error){return handleRouteError(error);}}
export async function PATCH(request:NextRequest,context:{params:Promise<{proposalId:string}>}){try{const{admin}=await requireAdmin(request,"governance.update");const{proposalId}=await context.params;const proposal=await GovernanceProposal.findById(proposalId);if(!proposal)throw new HttpError(404,"NOT_FOUND","Proposal not found.");const body=await readJson<any>(request);for(const key of ["title","propertyId","category","description","estimatedCost","closesAt","status","quorumPercent","eligibleVotes"] as const)if(body[key]!==undefined)(proposal as any)[key]=body[key];await proposal.save();await proposal.populate("propertyId","name");await recordActivity({request,admin,action:"Updated governance proposal",operation:"update",resourceType:"governance_proposal",resourceId:proposalId,resourceName:proposal.title});return ok(await withStats(proposal,String(admin._id)));}catch(error){return handleRouteError(error);}}
export async function DELETE(request:NextRequest,context:{params:Promise<{proposalId:string}>}){try{const{admin}=await requireAdmin(request,"governance.delete");const{proposalId}=await context.params;const proposal=await GovernanceProposal.findById(proposalId);if(!proposal)throw new HttpError(404,"NOT_FOUND","Proposal not found.");await Promise.all([GovernanceVote.deleteMany({proposalId}),proposal.deleteOne()]);await recordActivity({request,admin,action:"Deleted governance proposal",operation:"delete",resourceType:"governance_proposal",resourceId:proposalId,resourceName:proposal.title});return noContent();}catch(error){return handleRouteError(error);}}
