"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "nextjs-toploader/app";

import { type ListingKind } from "@/app/(app)/create-listing/create-listing-wizard-data";
import { FieldLabel, SelectField, inputClass } from "@/app/(app)/create-listing/wizard-form-primitives";
import { WizardFormFooter } from "@/app/(app)/create-listing/wizard-form-footer";
import { ADMIN_ASSETS } from "@/app/components/admin-assets";
import { usePropertyWizard } from "@/contexts/property-wizard-provider";
import { useListingWizardHref } from "@/lib/property-wizard/use-listing-wizard-href";
import { useScopedAddPropertyDocumentMutation, useScopedRemovePropertyDocumentMutation } from "@/lib/property-wizard/use-scoped-property-api";
import { uploadAdminFile } from "@/lib/upload-file";
import { cn } from "@/lib/utils";

type PropertyManagementFormProps = { listingKind: ListingKind };
const AMENITIES = [{ id: "pool", label: "Pool" }, { id: "parking", label: "Parking" }, { id: "security", label: "Security" }, { id: "gym", label: "Gym" }, { id: "ac", label: "Air-conditioning" }, { id: "internet", label: "Internet" }, { id: "view", label: "Ocean / City view" }];
const EMPTY = { bedrooms: "", bathrooms: "", kitchens: "", livingRooms: "", builtArea: "", landSize: "", yearBuiltOrRenovated: "", furnishingStatus: "furnished", amenities: [] as string[], existingPartner: "", managerCompanyName: "", managementType: "third-party", operationalNotes: "" };
type FormState = typeof EMPTY;
function TextField({ label, value, onChange, type = "text", disabled }: { label: string; value: string; onChange: (value: string) => void; type?: string; disabled?: boolean }) { return <label className="flex flex-col gap-1"><FieldLabel>{label}</FieldLabel><input type={type} min={type === "number" ? "0" : undefined} step={type === "number" ? "any" : undefined} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} className={inputClass()} /></label>; }
export function PropertyManagementForm({ listingKind }: PropertyManagementFormProps) {
  const router = useRouter(); const listingWizardHref = useListingWizardHref(); const icons = ADMIN_ASSETS.createListing.rentalWizard; const legalIcons = ADMIN_ASSETS.createListing.legalDocumentation;
  const { propertyId, property, getSectionData, saveStep, isSaving, isEditable } = usePropertyWizard();
  const saved = getSectionData<Partial<FormState>>("propertyManagement"); const [form, setForm] = useState<FormState>({ ...EMPTY, ...saved, amenities: saved?.amenities ?? [] });
  const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const addDocument = useScopedAddPropertyDocumentMutation(); const removeDocument = useScopedRemovePropertyDocumentMutation();
  useEffect(() => { if (saved) setForm({ ...EMPTY, ...saved, amenities: saved.amenities ?? [] }); }, [saved]);
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  const agreement = property?.documents?.find((document) => document.type === "management_agreement");
  async function upload(file: File | undefined) { if (!file || !propertyId) return; setUploading(true); setMessage(""); try { const uploaded = await uploadAdminFile(file, `asset-union/properties/${propertyId}/management`); await addDocument.mutateAsync({ propertyId, body: { type: "management_agreement", title: file.name.replace(/\.[^.]+$/, ""), url: uploaded.url, storageKey: uploaded.publicId, action: "download" } }); setMessage("Management agreement uploaded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to upload agreement."); } finally { setUploading(false); if (inputRef.current) inputRef.current.value = ""; } }
  async function removeAgreement() { if (!propertyId || !agreement) return; try { await removeDocument.mutateAsync({ propertyId, documentId: agreement.id }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to remove agreement."); } }
  async function continueNext() { if (propertyId && isEditable) await saveStep("property-management", { propertyManagement: form }, listingKind); router.push(listingWizardHref(listingKind, "legal-ownership")); }
  return <div className="flex flex-col gap-6">
    <div className="grid gap-6 md:grid-cols-2"><TextField label="Bedrooms" type="number" value={form.bedrooms} onChange={(value) => update("bedrooms", value)} disabled={!isEditable} /><TextField label="Bathrooms" type="number" value={form.bathrooms} onChange={(value) => update("bathrooms", value)} disabled={!isEditable} /></div>
    <div className="grid gap-6 md:grid-cols-2"><TextField label="Kitchens" type="number" value={form.kitchens} onChange={(value) => update("kitchens", value)} disabled={!isEditable} /><TextField label="Living rooms" type="number" value={form.livingRooms} onChange={(value) => update("livingRooms", value)} disabled={!isEditable} /></div>
    <div className="grid gap-6 md:grid-cols-2"><TextField label="Built Area (sqm/sqft)" type="number" value={form.builtArea} onChange={(value) => update("builtArea", value)} disabled={!isEditable} /><TextField label="Land Size (sqm/sqft)" type="number" value={form.landSize} onChange={(value) => update("landSize", value)} disabled={!isEditable} /></div>
    <div className="grid gap-6 md:grid-cols-2"><TextField label="Year Built / Renovated" value={form.yearBuiltOrRenovated} onChange={(value) => update("yearBuiltOrRenovated", value)} disabled={!isEditable} /><SelectField label="Furnishing Status" value={form.furnishingStatus} onChange={(event) => update("furnishingStatus", event.target.value)} disabled={!isEditable}><option value="furnished">Furnished</option><option value="semi-furnished">Semi-furnished</option><option value="unfurnished">Unfurnished</option></SelectField></div>
    <div className="rounded-2xl border border-[#cfe2ec] p-3"><p className="mb-2 text-[12px] font-medium text-[#050a0e]">Amenities</p><div className="grid gap-2 sm:grid-cols-3">{AMENITIES.map((amenity) => { const on = form.amenities.includes(amenity.id); return <button key={amenity.id} type="button" disabled={!isEditable} onClick={() => update("amenities", on ? form.amenities.filter((id) => id !== amenity.id) : [...form.amenities, amenity.id])} aria-pressed={on} className={cn("flex items-center gap-2 rounded-2xl p-4 text-left text-[12px] transition-colors disabled:opacity-60", on ? "bg-[#f0f1fc]" : "bg-[#f9fafb]")}><img alt="" src={on ? icons.amenityCheckboxChecked : icons.amenityCheckboxUnchecked} width={15} height={14} />{amenity.label}</button>; })}</div></div>
    <SelectField label="Property Manager / Company Name (if available)" value={form.existingPartner} onChange={(event) => update("existingPartner", event.target.value)} disabled={!isEditable}><option value="">Select an already existing partner</option><option value="in-house">Asset Union in-house team</option></SelectField>
    <div className="grid gap-6 md:grid-cols-2"><TextField label="Property Manager / Company Name" value={form.managerCompanyName} onChange={(value) => update("managerCompanyName", value)} disabled={!isEditable} /><SelectField label="Management Type" value={form.managementType} onChange={(event) => update("managementType", event.target.value)} disabled={!isEditable}><option value="third-party">Third-party</option><option value="in-house">In-house</option></SelectField></div>
    <div className="grid gap-6 md:grid-cols-2"><label className="flex flex-col gap-1"><FieldLabel>Operational Notes</FieldLabel><textarea rows={5} value={form.operationalNotes} onChange={(event) => update("operationalNotes", event.target.value)} disabled={!isEditable} placeholder="Add information on tenant handling, bookings, or maintenance approach" className={cn(inputClass(), "h-[135px] resize-none py-3")} /></label><div className="flex flex-col gap-1"><FieldLabel>Management Agreement Uploaded</FieldLabel><input ref={inputRef} hidden type="file" accept="application/pdf,.pdf,image/*" onChange={(event) => void upload(event.target.files?.[0])} />{agreement ? <div className="mt-1 rounded-xl border border-[#cfe2ec] p-3"><div className="flex items-center justify-between gap-2"><a href={agreement.url} target="_blank" rel="noreferrer" className="flex min-w-0 items-center gap-2"><img alt="" src={legalIcons.pdfRowIcon} width={20} height={20} /><span className="truncate text-[12px] font-medium text-[#050a0e]">{agreement.title}</span></a><button type="button" onClick={() => void removeAgreement()} disabled={!isEditable || removeDocument.isPending} className="rounded-md p-1 hover:bg-[#f5f7f8] disabled:opacity-50"><img alt="" src={legalIcons.deleteRowIcon} width={20} height={20} /></button></div></div> : <button type="button" onClick={() => inputRef.current?.click()} disabled={!isEditable || uploading} className="flex min-h-[100px] w-full items-center justify-center gap-4 rounded-[12px] border border-dashed border-[#cfe2ec] p-4 text-left hover:bg-[#f5f7f8]/50 disabled:opacity-50"><img alt="" src={icons.uploadPlusCircle} width={40} height={40} /><span className="text-[12px] text-[#919191]">{uploading ? "Uploading…" : "Browse PDF or image (20MB max)"}</span></button>}</div></div>
    {message ? <p className="rounded-[12px] bg-[#edf4f8] px-3 py-2 text-[12px]">{message}</p> : null}
    <WizardFormFooter nextStepLine1="Proceed to the next step" nextStepLine2="Legal & Ownership" backHref={listingWizardHref(listingKind, "rental-economics")} continueLabel="Continue" isSubmitting={isSaving} onContinue={continueNext} />
  </div>;
}
